[[redirects]]
  from = "/*"
  to = "/error/404.html"
  status = 404
  
[[plugins]]
package = "@netlify/plugin-sitemap"

    [plugins.inputs]
    buildDir = "public"
    filePath = "sitemap.xml"
    changeFreq = "daily"
    priority = 1.0